### ISSUE TITLE
File not found error on MacOS:  PixelSize.ui not found

### ISSUE THREAD

**Issue by vmhacker** [andreassteffens/qgis-map-units-per-pixel#2]
### Problem:
Version 0.2.0 of the plugin failed to load on MacOS because the file `PixelSize.ui` can't be found.

### Reason:
Line 40 in [map-units-per-pixel/map_units_per_pixel.py:40][fref] contains a hard-coded backslash [<b>U+005C</b>] as a path separator character, but backslash is a valid file name character for the APFS filesystem:
>https://github.com/andreassteffens/qgis-map-units-per-pixel/blob/d85c8f96027ed98f6187dc26172f789a350614bb/map-units-per-pixel/map_units_per_pixel.py#L40

### Fix:
To fix this and maximize filesystem compatibility, change [map_units_per_pixel.py:40][fref] to:
```python
    strUiPath = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ui", "PixelSize.ui")
```

[fref]: https://github.com/andreassteffens/qgis-map-units-per-pixel/blob/d85c8f96027ed98f6187dc26172f789a350614bb/map-units-per-pixel/map_units_per_pixel.py#L40

**Comment by andreassteffens** [comment]
closed in a3fb9308aee7ac6ad300a509144059e415b498cd
